framework:
  messenger:
    default_bus: command.bus

    buses:
      command.bus:
        middleware:
          - App\Message\Middleware\AuditMiddleware
      event.bus: ~
      query.bus: ~

    failure_transport: failed

    transports:
      failed:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          auto_setup: false
          table_name: Messages
          queue_name: failed

      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        failure_transport: failed
        retry_strategy:
          max_retries: 3
          delay: 5000
          multiplier: 2
          max_delay: 0
        options:
          auto_setup: false
          table_name: Messages
          queue_name: default

    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: async
      Symfony\Component\Notifier\Message\ChatMessage: async
      Symfony\Component\Notifier\Message\SmsMessage: async

      # Route your messages to the transports
      # 'App\Message\YourMessage': async
