version: '3.9'

services:
  php-base:
    build:
      context: .
      dockerfile: Dockerfile
      target: local
      args:
        UID: ${UID:-10000}
        GID: ${GID:-10001}
    user: "${UID:-10000}:${GID:-10001}"
    environment:
      PHP_OPCACHE_ENABLE: ${OPCACHE_ENABLE}
      OPCACHE_ENABLE_CLI: ${OPCACHE_ENABLE_CLI}
      OPCACHE_ENABLE_FREQ: ${OPCACHE_ENABLE_FREQ}
      OPCACHE_VALIDATE_TIMESTAMPS: ${OPCACHE_VALIDATE_TIMESTAMPS}
      OPCACHE_MAX_ACCELERATED_FILES: ${OPCACHE_MAX_ACCELERATED_FILES}
      OPCACHE_MEMORY_CONSUMPTION: ${OPCACHE_MEMORY_CONSUMPTION}
      OPCACHE_MAX_WASTED_PERCENTAGE: ${OPCACHE_MAX_WASTED_PERCENTAGE}
      OPCACHE_INTERNED_STRINGS_BUFFER: ${OPCACHE_INTERNED_STRINGS_BUFFER}
      OPCACHE_FAST_SHUTDOWN: ${OPCACHE_FAST_SHUTDOWN}
      OPCACHE_PRELOAD: ${OPCACHE_PRELOAD}
    volumes:
      - .:/app
    networks:
      - webapp

  asset-base:
    working_dir: /app
    security_opt:
      - no-new-privileges:true
    profiles:
      - dev
    restart: "no"
    volumes:
      - .:/app

networks:
  webapp:
    driver: bridge
