name: PHPUnit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - '8.2'
          - '8.3'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: PHPUnit
        run: php vendor/bin/phpunit
